"""Demo: an MCP client asks the server for the lowest inlet pressure that meets a
target arrival time, then checks the answer.

    python mcp_server/demo_client.py              # ~1 min, writes demo_log.json / demo_log.md
    python mcp_server/demo_client.py --L 2000 --t-max 300

The client starts mcp_server/server.py as a subprocess and talks MCP over stdio,
exactly as Claude Desktop or Claude Code would.  If pigsim says the first answer
misses the target, it asks again with a 3-std instead of a 2-std margin.
"""

import argparse
import asyncio
import json
import os
import sys
import time

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

HERE = os.path.dirname(os.path.abspath(__file__))


async def run(L, t_max):
    params = StdioServerParameters(command=sys.executable, args=[os.path.join(HERE, "server.py")])
    log = []

    async with stdio_client(params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()

            async def call(name, args):
                t0 = time.perf_counter()
                res = await session.call_tool(name, args)
                out = json.loads(res.content[0].text)
                log.append({"tool": name, "arguments": args, "result": out,
                            "seconds": round(time.perf_counter() - t0, 2)})
                return out

            tools = await session.list_tools()
            log.append({"tool": "list_tools", "result": [t.name for t in tools.tools]})
            await call("describe_model", {})
            design = await call("inverse_design", {"L_m": L, "t_max_s": t_max})
            # the optimum sits on the constraint boundary; if pigsim says it misses,
            # ask again with a wider safety margin (3 std instead of 2)
            if design.get("status") == "ok" and not design.get("pigsim_check", {}).get("meets_targets"):
                design = await call("inverse_design", {"L_m": L, "t_max_s": t_max, "k_sigma": 3.0})
            if design.get("status") == "ok":
                b = design["best"]
                lower = {"p_in_bar": round(b["p_in_bar"] - 0.2, 3), "mass_kg": b["mass_kg"],
                         "F_fric_kN": b["F_fric_kN"], "L_m": L}
                # is 0.2 bar less really too little?  ask the surrogate, then pigsim
                await call("predict", lower)
                await call("run_pigsim", lower)
    return log


def write_md(log, path, L, t_max):
    lines = [f"# MCP demo: lowest inlet pressure for L = {L:g} m, t_arrive <= {t_max:g} s", "",
             "Generated by `python mcp_server/demo_client.py`. Each step is one MCP tool call "
             "over stdio.", ""]
    for k, e in enumerate(log, 1):
        lines.append(f"## {k}. `{e['tool']}`" + (f"  ({e['seconds']} s)" if "seconds" in e else ""))
        if "arguments" in e:
            lines += ["", "arguments:", "```json", json.dumps(e["arguments"], indent=2), "```"]
        lines += ["", "result:", "```json", json.dumps(e["result"], indent=2), "```", ""]
    with open(path, "w") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--L", type=float, default=2000.0)
    ap.add_argument("--t-max", type=float, default=300.0)
    args = ap.parse_args()
    log = asyncio.run(run(args.L, args.t_max))
    with open(os.path.join(HERE, "demo_log.json"), "w") as f:
        json.dump(log, f, indent=2)
    write_md(log, os.path.join(HERE, "demo_log.md"), args.L, args.t_max)
    for d in [e["result"] for e in log if e["tool"] == "inverse_design"]:
        if d.get("status") != "ok":
            continue
        b, c = d["best"], d.get("pigsim_check", {})
        print(f"k_sigma {d['problem']['k_sigma']}: p_in {b['p_in_bar']:.3f} bar, mass {b['mass_kg']:.0f} kg, F {b['F_fric_kN']:.2f} kN; "
              f"surrogate t {b['predicted']['t_arrive_s']:.1f} s; pigsim t {c.get('t_arrive_s')} s, "
              f"meets target: {c.get('meets_targets')}")
    lower = [e for e in log if e["tool"] in ("predict", "run_pigsim")]
    for e in lower:
        r = e["result"]
        t = r["t_arrive_s"]["mean"] if e["tool"] == "predict" else r.get("t_arrive_s")
        print(f"  0.2 bar lower -> {e['tool']}: t_arrive {t}")
    print("-> demo_log.json, demo_log.md")


if __name__ == "__main__":
    main()
